// All routes from App.tsx - SINGLE SOURCE OF TRUTH
export const routes = [
  "/",
  "/glass-company-las-vegas",
  "/glass-company-las-vegas/residential-glass-repair",
  "/glass-company-las-vegas/office-enclosures",
  "/shower-doors-las-vegas",
  "/shower-doors-las-vegas/frameless",
  "/shower-doors-las-vegas/semi-frameless-framed",
  "/shower-doors-las-vegas/sliding",
  "/shower-doors-las-vegas/hinged",
  "/shower-doors-las-vegas/custom-enclosures",
  "/shower-doors-las-vegas/steam-enclosures",
  "/shower-enclosures-las-vegas",
  "/gallery",
  "/areas-served",
  "/about",
  "/resources",
  "/contact",
  "/sitemap",
  "/reviews",
  "/faq",
  "/shower-doors-henderson-nv",
  "/shower-doors-summerlin-nv",
  "/shower-doors-paradise-nv",
  "/shower-doors-spring-valley-nv",
  "/shower-doors-enterprise-nv",
  "/shower-doors-green-valley-nv",
  "/blog",
  "/blog/glass-care-guide",
  "/blog/choosing-right-door",
  "/blog/installation-process",
  "/blog/warranty-information",
  "/blog/shower-door-installation-cost-las-vegas",
  "/blog/frameless-vs-semi-frameless-shower-doors",
  "/blog/las-vegas-water-quality-shower-glass-hard-water-solutions",
  "/shower-door-replacement-las-vegas"
];

export const domain = 'https://bajaglass.com';
