// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amuicwvoacadtcjtegzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtdWljd3ZvYWNhZHRjanRlZ3pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MjU3MDEsImV4cCI6MjA3MzIwMTcwMX0.QS_GV5b0Vzu6S3-qv0RrZGIPfSXOsBK0f05DgQkQ-1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});