// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzeuuhbrtjykwcatafyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6ZXV1aGJydGp5a3djYXRhZnlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzc0NTIsImV4cCI6MjA3MzcxMzQ1Mn0.Hwo172F32XCwAV9sOuB9zOIiyZPS7AdmaXgPPSBpC0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});