/**
 * Single source of truth for Baja Glass business facts and JSON-LD generation.
 *
 * PROVENANCE RULE: every factual claim in here must either (a) already appear on
 * the live site, or (b) carry the TODO marker below. Nothing gets invented —
 * no pricing, no job counts, no warranty terms, no years in business.
 *
 * Schema is generated by the helpers at the bottom of this file. Do not
 * hand-write JSON-LD anywhere in the render tree, and never emit more than one
 * LocalBusiness node per page (see `localBusinessSchema`).
 */

/** Marker for claims that could not be confirmed against the live site. */
export const TODO = "{{TODO: confirm with Cliff}}";

export const BUSINESS = {
  name: "Baja Glass & Mirror LLC",
  url: "https://bajaglass.com",
  phoneDisplay: "(702) 383-0779",
  phoneHref: "tel:+17023830779",
  address: {
    street: "4280 W Reno Ave Ste A",
    city: "Las Vegas",
    region: "NV",
    postalCode: "89118",
    country: "US",
  },
  geo: { latitude: 36.097781, longitude: -115.197234 },

  /**
   * 4.7 / 42 confirmed by the client this session, superseding the 4.6 / 27 that
   * was hardcoded across the site and the conflicting 27-vs-33 figures in live
   * ad copy.
   */
  rating: { value: "4.7", count: "42", best: "5", worst: "1" },

  /**
   * Hours: visible copy and 3 of 5 existing schema blocks say 8am–4pm. Two
   * stale blocks said 17:00; 16:00 is the correct close.
   */
  hours: { days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], opens: "08:00", closes: "16:00" },

  /** Verified on the live site. */
  founded: "1999",
  licenseType: "C8 Glass & Glazing",
  licenseAuthority: "Nevada State Contractors Board",
  /** No license NUMBER appears anywhere on the live site. */
  licenseNumber: TODO,
  insured: "Bonded and insured, with general liability coverage",
  ownership: "Family owned and first-responder owned, owner-operated since 1999",
  crew: "In-house installers — we do not subcontract",
  hardwareWarranty: "Lifetime warranty on all hardware",
  glassWarranty: "Manufacturer warranty against defects in the glass",
  workmanshipWarranty: "Workmanship warranty on every installation",
  /** Live ads claim a specific parts-and-labor term the site does not state. */
  laborWarrantyTerm: TODO,
  leadTime: "Most doors installed 7–14 days after your measure",
  measure: "Free in-home measure",

  serviceAreas: [
    "Las Vegas",
    "Summerlin",
    "Henderson",
    "North Las Vegas",
    "Spring Valley",
    "Paradise",
    "Enterprise",
    "Green Valley",
    "Boulder City",
  ],
} as const;

/** Areas named explicitly in the page's H2, used for schema areaServed. */
export const PRIMARY_AREAS = [
  "Las Vegas",
  "Summerlin",
  "Henderson",
  "North Las Vegas",
  "Spring Valley",
] as const;

export interface Faq {
  q: string;
  a: string;
}

const postalAddress = () => ({
  "@type": "PostalAddress",
  streetAddress: BUSINESS.address.street,
  addressLocality: BUSINESS.address.city,
  addressRegion: BUSINESS.address.region,
  postalCode: BUSINESS.address.postalCode,
  addressCountry: BUSINESS.address.country,
});

/**
 * The single LocalBusiness node. Every other node references it by @id rather
 * than nesting its own copy, so a page can never emit two LocalBusiness blocks.
 */
export const LOCAL_BUSINESS_ID = `${BUSINESS.url}/#localbusiness`;

export const localBusinessSchema = () => ({
  "@type": "LocalBusiness",
  "@id": LOCAL_BUSINESS_ID,
  name: BUSINESS.name,
  url: BUSINESS.url,
  telephone: BUSINESS.phoneDisplay,
  address: postalAddress(),
  geo: {
    "@type": "GeoCoordinates",
    latitude: BUSINESS.geo.latitude,
    longitude: BUSINESS.geo.longitude,
  },
  aggregateRating: {
    "@type": "AggregateRating",
    ratingValue: BUSINESS.rating.value,
    reviewCount: BUSINESS.rating.count,
    bestRating: BUSINESS.rating.best,
    worstRating: BUSINESS.rating.worst,
  },
  priceRange: "$$",
  foundingDate: BUSINESS.founded,
  openingHoursSpecification: [
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: [...BUSINESS.hours.days],
      opens: BUSINESS.hours.opens,
      closes: BUSINESS.hours.closes,
    },
  ],
});

export const serviceSchema = (pageUrl: string) => ({
  "@type": "Service",
  "@id": `${pageUrl}#service`,
  name: "Frameless Shower Door Installation",
  serviceType: "Frameless Shower Door Installation",
  description:
    "Custom frameless glass shower doors for Las Vegas homes — measured in your bathroom, fabricated to your opening, and installed by in-house licensed installers.",
  provider: { "@id": LOCAL_BUSINESS_ID },
  areaServed: PRIMARY_AREAS.map((name) => ({
    "@type": "City",
    name,
    addressRegion: BUSINESS.address.region,
  })),
});

export const faqPageSchema = (faqs: readonly Faq[]) => ({
  "@type": "FAQPage",
  mainEntity: faqs.map((faq) => ({
    "@type": "Question",
    name: faq.q,
    acceptedAnswer: { "@type": "Answer", text: faq.a },
  })),
});

/**
 * Builds the complete @graph for a page: exactly one LocalBusiness, one
 * Service, one FAQPage.
 */
export const buildPageSchema = (pageUrl: string, faqs: readonly Faq[]) => ({
  "@context": "https://schema.org",
  "@graph": [localBusinessSchema(), serviceSchema(pageUrl), faqPageSchema(faqs)],
});
